### PR TITLE
Minecraft1112

### PR DESCRIPTION
**Pull request by ruitaomu**
Build against Forge 1.11.2

### CODE REVIEW

**Comment by ruitaomu** [comment]
Hi! I just did a porting of PythonTool to 1.11.2, there're some conflictions but not serious. Mostly they are asset files, I found their names have to be all in lower-case characters, or not being loaded.
Main changes are using EMPTY items instead of null.
I also made a 1.12.2 porting, if you think it's ok, I'll create another PR for that.

Best Regards,
M@x

**Comment by alvaropp** [comment]
Hi Max, that's great!

I haven't played Minecraft for a good while now so your help is much appreciated. The port to 1.12.2 would be welcome as well.

I'll have a look tomorrow Friday or in the weekend.

**Comment by alvaropp** [comment]
I'm curious about the 1.12.2 port. Looking at raspberyjam mod, it seems that the most recent version is 1.11.2. Did you update that one to 1.12.2 as well?

**Comment by ruitaomu** [comment]
https://github.com/arpruss/raspberryjammod
You can see it has 112 (1.12) folder in the source tree.  If you download the latest 0.94 release mod binary, 1.12 is there. That's what I have tested with.

**Comment by alvaropp** [comment]
Hi, that makes sense, thanks!

**Review by alvaropp — COMMENTED** [review]
I've built the mod for 1.11.2 and it seems to work fine. There are a few issues though.

Main things:

- There's a problem with the computer block and the script item's names

- When placing the computer block on the ground it always faces the same direction, so that it doesn't face the player. I think you have commented out the code that achieved this.

Other things:
- I'm seeing that there are a lot of auxiliary files (like eclipse settings). Can you remove those and just include the source code? As an example of what to include, you can have a look at the 1.10.2 version: https://github.com/ngcm/PythonTool-Mod/tree/minecraft1102

- Also, note that this PR should go to the `minecraft1112` branch, not `master`. I have just changed this.

These also apply your other PR.

Thanks a lot!

**Comment by ruitaomu** [comment]
Regarding to the issue 1, I found that it's because of capitalized characters in resource names in en_us.lang. I made these changes in 1.12.2 implementation but forgot to backport to 1.11.2, thanks for checking! Here I attach the en_us.lang file, but should I create a new pull request which includes this change?
[en_us.zip](https://github.com/ngcm/PythonTool-Mod/files/4732674/en_us.zip)

But for issue 2, I've no idea yet.

**Comment by ruitaomu** [comment]
One more thing:
Because I'm using this mod in both SP and MP game modes (via Forge/Sponge server), so I've removed the reference of Minecraft.getMinecraft().player.capabilities.isCreativeMode in ComputerBlock.breakBlock(). But it results in dropping ComputerBlock itself when it's broken regardless creative mode or not. Don't know if you like this so it's not included in this PR now.

**Comment by alvaropp** [comment]
Hi Max, regarding the new language file, push your changes to this branch and the PR will be updated automatically.

Concerning the ComputerBlock breaking, I'm easy. Sadly I don't have a lot of time to work on this at the moment so if you are happy with that behaviour and the mod is usable as intended, no problem there.

Regarding the ComputeBlock facing always the same direction, perhaps this is something that has changed in these new versions of Minecraft 🤔  I remember it took me a while to get right back then.

Thanks!

**Comment by ruitaomu** [comment]
Hi Alvaopp, just removed eclipse-related files, please give a review to see if it's going to be merged ready?
Thanks,
Max

**Comment by alvaropp** [comment]
Hi Max, cool, the names are fixed and it all seems fine. I guess the only thing is the direction the ComputerBlock is facing when placed on the ground, but that's something that can be fixed in the future. I'll approve and we can merge.

**Pull request merged**
